# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tC7FdieESQZJSmNdPnlQ77BZBi3J30xR
"""

a=int(input("Nota 1: "))*0.30
b=int(input("Nota 2: "))*0.15
c=int(input("Nota 3: "))*0.15
d=int(input("Nota 4: "))*0.20
e=int(input("Nota 5: "))*0.20
if ((a+b+c+d+e)/5)>=3:
    print("Aprobado")
print((a+b+c+d+e)/5)

a=int(input("Numero A: "))
b=int(input("Numero B: "))
if a>b:
    print("A es mayor a B")
if a<b:
    print("A es menor a B")
if a==b:
    print("A es igual a B")

